### ISSUE TITLE
¿Qué es la disponibilidad del candidato?

### ISSUE THREAD

**Issue by MarioGuisado** [manuelvico0102/easySelect#10]
Según #3 , se debe guardar la "disponibilidad" del candidato. El problema consiste en guardar y detallar, dentro de un rango, la disponibilidad del candidato, de forma que más tarde se pueda procesar y filtrar dicho dato.

**Comment by JJ** [comment]
No especificas qué significa la disponibilidad y qué implicación va a tener en la lógica de negocio.
