### ISSUE TITLE
¿Qué información se va a extraer?

### ISSUE THREAD

**Issue by MarioGuisado** [manuelvico0102/easySelect#15]
¿Cuales son los datos que vamos a extraer dadas #3 y #5, y de qué forma se van a proporcionar?

**Comment by JJ** [comment]
Estás solucionando esto con un fichero, que podía ser el ejemplo para el objetivo 4. Pero lo que solucionaría este issue sería un modelo de dónde va a estar ese fichero y qué metadatos va a tener, como hemos hablado en clase.

**Comment by MarioGuisado** [comment]
@JJ Supongo que no es necesario crear una clase para representar los metadatos del fichero, puesto que estos datos serán los que tiene la clase Candidato, sería crear dos clases con atributos "repetidos". Por esto no entiendo bien como suministrar este "modelo", ¿debo modificar el constructor de la clase Candidato para que lea este fichero? O por el contrario, dado que se debe especificar la localización del fichero, así como sus datos (la forma en la que está construido),   bastaría con especificar en el readme.md, en una sección nueva, cómo se guardará el fichero y la estructura que tendrá.

**Comment by JJ** [comment]
No puede suponerlo, tienes que plantear el problema. Sobre todo, @manuelvico0102 tiene que mirar un poco qué es lo que va a hacer exactamente con este modelo. Su problema es principalmente extraer información, no colocar esa información en una u otra variable, que es más o menos trivial. ¿Qué hay en este modelo sobre la extracción de información? Me da la impresión que nada. Si ahora mismo @manuelvico0102 tuviera que ponerse a programar la lógica de negocio, ¿qué de todo este modelo podría usar? Me da la impresión de que nada, porque no hay nada que represente la entrada al modelo, el texto, nada que represente cómo se podría extraer cada una de las cosas, o siquiera reconocer si están en el texto o no.
Permitidme que insista en que lo principal de este modelo es *la lógica de negocio*, no *el resultado de la lógica de negocio*, que es lo único que hay ahora mismo en el PR.
