### ISSUE TITLE
Test para lógica de negocio

### ISSUE THREAD

**Issue by manuelvico0102** [manuelvico0102/easySelect#22]
Una vez elegidas las herramientas de test #21, será necesario implementar un test para la principal lógica de negocio de nuestro proyecto y así conseguir resolver #3 y validar el milestone 1.

**Comment by JJ** [comment]
Los issues son siempre problemas, no tareas. "Implementación de" no puede ser nunca el título de un issue.
Pero si se trata de tests, menos todavía. Los tests siempre se tienen que crear para comprobar que la lógica de negocio funciona. Y en cuanto a [a4bcb9c](https://github.com/manuelvico0102/easySelect/commit/a4bcb9c70d525f37b9b049d5baba28e4c049a833) en general los getters (o lo que sea) se tienen que justificar por la lógica de negocio, no porque lo necesite un test. Si un test necesita un getter, es que quizás no estás testeando al nivel correcto.

**Comment by manuelvico0102** [comment]
Solucionado para testear en el nivel correcto en 2a74cf9bfef8a0afa09412fa8480baca65aee41a
