### ISSUE TITLE
Archivos para extracción de datos

### ISSUE THREAD

**Issue by manuelvico0102** [manuelvico0102/easySelect#24]
Se necesitan archivos que contengan información de un candidato necesarios para posibles casos de #3.

**Comment by JJ** [comment]
En general, el crear issues en cascada puede plantear una serie de problemas porque acabas alejándote de lo que desea el cliente y se puede caer en la creación de código (o ficheros auxiliares) que no tengan mucho que ver con el mismo. En este caso, si planteas los ficheros para la implementación (#22, que ya he comentado que es incorrecto), no vas a crearlo para la historia de usuario correspondiente, y por tanto pueden ser incorrectos.
