### ISSUE TITLE
¿Como representar el conocimiento de idiomas y lenguajes de programación?

### ISSUE THREAD

**Issue by MarioGuisado** [manuelvico0102/easySelect#9]
En #3 , uno de los problemas generados es almacenar y detallar el nivel de conocimiento de lenguajes de programación e idiomas. ¿Cómo guardar dicha información, de forma que además se especifique el grado de conocimiento? En #5  esta información será vital para poder filtrar correctamente a los candidatos.

**Comment by JJ** [comment]
El problema no es sólo como guardarlo, es como expresarlo.
